apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2025-01-03T14:45:16.134804825Z"
    description: A Helm chart for Pathling Server
    digest: c09642759c16f06ca9c65c0f0115688ed780021050f58af1cf2ff08d56ad2251
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.2.tgz
    version: 1.0.2
generated: "2025-01-03T14:45:16.134236962Z"
