apiVersion: v1
entries:
  pathling:
  - apiVersion: v2
    created: "2025-05-01T10:00:31.676993972Z"
    description: A Helm chart for Pathling Server
    digest: 4c8d36ec6f36bf498b550bef177a19010eb99b45c21ce3227d93e5777e1c3737
    icon: https://raw.githubusercontent.com/aehrc/pathling/main/media/logo-icon-colour-detail.svg
    keywords:
    - spark
    - analytics
    - standards
    - fhir
    - terminology
    maintainers:
    - email: John.Grimes@csiro.au
      name: John Grimes
    name: pathling
    sources:
    - https://github.com/aehrc/pathling
    type: application
    urls:
    - https://pathling.csiro.au/helm/pathling-1.0.2.tgz
    version: 1.0.2
generated: "2025-05-01T10:00:31.67617922Z"
